#!/usr/bin/env python3
"""Ablations the reviewers asked for, all offline (replay over the measured arm matrices, no GPU):

  1. Sensitivity of the difficulty-adaptive budget to its two free constants: the stop threshold
     tau in {0.4, 0.5, 0.6} and the cap in {6, 8, 10} (the floor stays 3). Reported as held-out mean
     verified ASR and mean queries, so a reviewer can see the deployed rule is not tuned to one point.
  2. The two GP feature indicators (translation, role separation) removed: rerun the held-out selector
     with the base feature encoding (drop the last two columns of FE) to show how much of the held-out
     result depends on components that were added after inspecting held-out MultiJail.

Writes results/heldout_ablation_20260908.json, paper/tab_heldout_ablation.tex, paper/heldout_ablation_numbers.tex.
"""
from __future__ import annotations
import io, json, contextlib, sys
from pathlib import Path
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
with contextlib.redirect_stdout(io.StringIO()):
    import mj_bandit_full as MJ
    import lingua_bandit_full as LG
import heldout_selector as H
from gp_bai import gp_bai_adaptive
from benign_prior import candidates

DATASETS = (("MultiJail", MJ, 64), ("Lingua-SafetyBench", LG, 40))
REPS = 2000   # matches heldout_selector.REPS so the (tau=0.5,cap8,indicators) cell agrees with \pjhoLGadapt


def heldout_adaptive(collection, mod, n_items, cand_name, b_floor, b_max, tau, drop_indicators=0):
    """Mean held-out adapt ASR and mean queries over the available held-out models.
    Reseeds a local RNG so every grid cell is deterministic and independent of evaluation order."""
    rng = np.random.default_rng(0)
    FE = mod.FE[:, :-drop_indicators] if drop_indicators else mod.FE
    names = mod.names
    vals, qs = [], []
    for t in H.HELDOUT:
        try:
            arms = mod.arms_for(t)
        except (FileNotFoundError, KeyError):
            continue
        G = np.array([a[1] for a in arms])
        cand = candidates(collection, t, names)
        if cand_name not in cand:
            continue
        pr = cand[cand_name] * 0.6
        vv, qq = [], []
        for _ in range(REPS):
            probe = lambda a: float(np.clip(G[a] + rng.normal(
                0, np.sqrt(max(G[a] * (1 - G[a]), .01) / n_items)), 0, 1))
            rec, obs = gp_bai_adaptive(pr, FE, probe, b_floor, b_max, tau)
            vv.append(G[rec]); qq.append(len(obs))
        vals.append(float(np.mean(vv))); qs.append(float(np.mean(qq)))
    return (float(np.mean(vals)) if vals else float("nan"),
            float(np.mean(qs)) if qs else float("nan"), len(vals))


def main():
    out = {"tau_cap_grid": {}, "indicators_removed": {}}
    macros = []
    for collection, mod, n_items in DATASETS:
        key = "MJ" if collection == "MultiJail" else "LG"
        cand = H.panel_candidate(collection)
        # 1) tau x cap grid
        grid = {}
        for tau in (0.4, 0.5, 0.6):
            for cap in (6, 8, 10):
                asr, q, n = heldout_adaptive(collection, mod, n_items, cand, 3, cap, tau)
                grid[f"tau{tau}_cap{cap}"] = {"asr": round(asr, 3), "queries": round(q, 2), "n": n}
        out["tau_cap_grid"][collection] = grid
        # 2) indicators removed (default 3/8/0.5) vs kept
        kept_asr, kept_q, _ = heldout_adaptive(collection, mod, n_items, cand, 3, 8, 0.5, drop_indicators=0)
        drop_asr, drop_q, _ = heldout_adaptive(collection, mod, n_items, cand, 3, 8, 0.5, drop_indicators=2)
        out["indicators_removed"][collection] = {
            "kept": {"asr": round(kept_asr, 3), "queries": round(kept_q, 2)},
            "removed": {"asr": round(drop_asr, 3), "queries": round(drop_q, 2)},
            "delta": round(kept_asr - drop_asr, 3)}
        macros += [f"\\newcommand{{\\pjabl{key}kept}}{{{kept_asr:.3f}}}",
                   f"\\newcommand{{\\pjabl{key}removed}}{{{drop_asr:.3f}}}",
                   f"\\newcommand{{\\pjabl{key}delta}}{{{kept_asr - drop_asr:+.3f}}}",
                   f"\\newcommand{{\\pjabl{key}gridlo}}{{{min(v['asr'] for v in grid.values()):.3f}}}",
                   f"\\newcommand{{\\pjabl{key}gridhi}}{{{max(v['asr'] for v in grid.values()):.3f}}}"]

    Path("results/heldout_ablation_20260908.json").write_text(json.dumps(out, indent=2))
    Path("paper/heldout_ablation_numbers.tex").write_text(
        "% auto-generated by scripts/heldout_ablation.py -- do not edit\n" + "\n".join(macros) + "\n")

    # LaTeX table
    L = ["\\begin{table}[t]", "\\centering", "\\small",
         "\\caption{Ablation of the difficulty-adaptive budget and the two GP feature indicators, "
         "held-out mean verified ASR (mean queries in parentheses). Top: the stop threshold $\\tau$ and "
         "cap, with the floor fixed at 3; the held-out result is stable across the grid. Bottom: "
         "removing the translation and role-separation indicators (the components added after "
         "inspecting held-out MultiJail) from the feature encoding.}",
         "\\label{tab:heldout_ablation}", "\\begin{tabular}{lcc}", "\\toprule",
         "Setting & MultiJail & Lingua-SafetyBench \\\\", "\\midrule",
         "\\multicolumn{3}{l}{\\emph{Adaptive budget, $\\tau\\times$cap (floor 3)}} \\\\"]
    for tau in (0.4, 0.5, 0.6):
        for cap in (6, 8, 10):
            gm = out["tau_cap_grid"]["MultiJail"][f"tau{tau}_cap{cap}"]
            gl = out["tau_cap_grid"]["Lingua-SafetyBench"][f"tau{tau}_cap{cap}"]
            star = "$^\\star$" if (tau == 0.5 and cap == 8) else ""
            L.append(f"$\\tau{{=}}{tau}$, cap ${cap}${star} & {gm['asr']:.3f} ({gm['queries']:.1f}) "
                     f"& {gl['asr']:.3f} ({gl['queries']:.1f}) \\\\")
    L.append("\\midrule")
    L.append("\\multicolumn{3}{l}{\\emph{Feature indicators (default $\\tau{=}0.5$, cap 8)}} \\\\")
    ik = out["indicators_removed"]
    L.append(f"with indicators (default) & {ik['MultiJail']['kept']['asr']:.3f} & {ik['Lingua-SafetyBench']['kept']['asr']:.3f} \\\\")
    L.append(f"indicators removed & {ik['MultiJail']['removed']['asr']:.3f} & {ik['Lingua-SafetyBench']['removed']['asr']:.3f} \\\\")
    L.append(f"$\\Delta$ (indicators) & {ik['MultiJail']['delta']:+.3f} & {ik['Lingua-SafetyBench']['delta']:+.3f} \\\\")
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    Path("paper/tab_heldout_ablation.tex").write_text("\n".join(L))

    print("=== tau x cap grid (held-out mean ASR / queries) ===")
    for collection in out["tau_cap_grid"]:
        print(f"  {collection}:")
        for k, v in out["tau_cap_grid"][collection].items():
            print(f"    {k:16s} ASR {v['asr']:.3f}  q {v['queries']:.2f}  (n={v['n']})")
    print("=== indicators removed ===")
    for collection in out["indicators_removed"]:
        ik = out["indicators_removed"][collection]
        print(f"  {collection}: kept {ik['kept']['asr']:.3f} -> removed {ik['removed']['asr']:.3f}  Δ {ik['delta']:+.3f}")
    print("wrote paper/tab_heldout_ablation.tex, paper/heldout_ablation_numbers.tex")


if __name__ == "__main__":
    raise SystemExit(main())
