#!/usr/bin/env python3
"""Robustness of the perplexity-stealth comparison to the reference model and to the scaffold
(reviewer W8). We (i) re-score prompt perplexity under a NON-Qwen reference (Llama-3.1-8B-Instruct),
since Qwen is the reconstruction judge and target family, and (ii) score the PAYLOAD ONLY of our
interleaving -- the mixed multilingual paragraph after the "MIXED PARAGRAPH" marker, with the
repetitive reconstruction scaffold removed -- to check whether our low prompt PPL is an artifact of
the boilerplate. Forward pass only, no generation. Writes paper/ppl_nonqwen_numbers.tex and
results/ppl_nonqwen_20260908.json."""
from __future__ import annotations
import json, sys, math
from pathlib import Path
import numpy as np
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

sys.path.insert(0, str(Path(__file__).resolve().parent))
import ppl_evasion as PE

REF = "meta-llama/Llama-3.1-8B-Instruct"   # non-Qwen reference


def pick_device():
    best, bestfree = 0, -1
    for i in range(torch.cuda.device_count()):
        free, _ = torch.cuda.mem_get_info(i)
        if free > bestfree:
            best, bestfree = i, free
    return best, bestfree


@torch.no_grad()
def ppl(model, tok, text):
    ids = tok(text, return_tensors="pt", truncation=True, max_length=2048).input_ids.to(model.device)
    if ids.shape[1] < 2:
        return float("nan")
    out = model(ids, labels=ids)
    return float(math.exp(min(out.loss.item(), 20)))


def payload_only(prompt):
    """The mixed multilingual paragraph, with the reconstruction scaffold stripped."""
    marker = "MIXED PARAGRAPH"
    return prompt.split(marker, 1)[1].strip() if marker in prompt else prompt


def main():
    methods = PE.load_prompts()
    dev, free = pick_device()
    print(f"using cuda:{dev} ({free/1e9:.1f} GB free)")
    tok = AutoTokenizer.from_pretrained(REF, local_files_only=True)
    model = AutoModelForCausalLM.from_pretrained(
        REF, torch_dtype=torch.bfloat16, local_files_only=True).to(f"cuda:{dev}").eval()

    res = {}
    for name, prompts in methods.items():
        vals = [ppl(model, tok, p) for p in prompts if p]
        vals = [v for v in vals if v == v]
        res[name] = dict(median=float(np.median(vals)), p90=float(np.percentile(vals, 90)), n=len(vals))
        print(f"  full   {name:28s} median {res[name]['median']:7.1f}  p90 {res[name]['p90']:7.1f}  n={res[name]['n']}")

    # payload-only for our interleaving vs plain English request (already payload-like)
    ours = methods["interleave $n{=}4$ (ours)"]
    pay = [ppl(model, tok, payload_only(p)) for p in ours if p]
    pay = [v for v in pay if v == v]
    res["interleave payload-only"] = dict(median=float(np.median(pay)), p90=float(np.percentile(pay, 90)), n=len(pay))
    print(f"  payload interleave (ours)     median {res['interleave payload-only']['median']:7.1f}  "
          f"p90 {res['interleave payload-only']['p90']:7.1f}")

    Path("results/ppl_nonqwen_20260908.json").write_text(json.dumps(res, indent=2))

    def rnd(k):
        return int(round(res[k]["median"]))
    ours_key = "interleave $n{=}4$ (ours)"
    pairs = [("pjpplnqours", ours_key), ("pjpplnqplain", "plain (English)"),
             ("pjpplnqtrans", "translation (Finnish)"), ("pjpplnqdrattack", "DrAttack"),
             ("pjpplnqflip", "FlipAttack (FCS)"), ("pjpplnqpayload", "interleave payload-only")]
    macros = [f"\\newcommand{{\\{name}}}{{{rnd(key)}}}" for name, key in pairs]
    Path("paper/ppl_nonqwen_numbers.tex").write_text(
        "% auto-generated by scripts/ppl_nonqwen.py -- do not edit\n" + "\n".join(macros) + "\n")
    print("wrote paper/ppl_nonqwen_numbers.tex")


if __name__ == "__main__":
    raise SystemExit(main())
